### ISSUE TITLE
Wiki Page Home

### ISSUE THREAD

**Issue by ajansel** [laujonat/clickr#1]
# Wiki Page Home

- [x] Is the first page you see upon entering the wiki
- [x] Contains a welcome message
- [x] Contains a link/placeholder for a link to the live page
  - This can just be a link to GitHub, App Academy, or Heroku main page for now and then once you have a live link you can change it.
- [x] All links in the right sidebar should contain each wiki page and link to the correct page
- [x] Correctly formatted
    - [x] each wiki page is listed in bullet points
      - I would recommend changing them to bullets rather than numbers since they aren't technically in a numbered order in terms of organization or methodology  
      - I would also recommend not using back ticks the naming here 
    - [x] all links route the correct page

# Comments:
- This is more so about the entire repo rather than the wiki homepage specifically but your rails directory should be your top level directory, not the `clickr` folder. For example if you got to [bluebird](https://github.com/appacademy/bluebird) notice that it's immediately the rails project directory root. 
- Looks good so far! Once you do the above, comment on here to let me know and then I can close the issue!

**Comment by laujonat** [comment]
Fixed the above formatting issues. Thank you!

**Comment by ajansel** [comment]
No prob! Should be good here. I can help you with the repo in our 1-on-1. Done here
