### ISSUE TITLE
MVP List

### ISSUE THREAD

**Issue by ajansel** [laujonat/clickr#2]
# MVP List

- [x] Should have 7 MVPs.
    - [x] 3 of those are User Auth, Heroku, and Production README.
    - [x] The other 4 are from the [MVP List](https://github.com/appacademy/curriculum/blob/master/full-stack-project/proposal/mvp-list.md) or they have clarified them with you
- [x] Contains a description sentence of the app
  - Make sure to add this 
- [x] At least one CRUD feature, which states what CRUD operations are planned (creation, reading, updating, deletion)
  - Photos and albums needs to include deleting (so that they're full CRUD)
  - Comments needs to include updating and deleting (so that it's full CRUD)
- [x] Estimates how long it will take the code each MVP
  - This still needs to be added. We can discuss this together this afternoon but for now maybe put your estimate and then we can update it when we meet.
- [x] Each App specific MVP needs the following bullet points are added:
    + Adequate styling
    + Smooth, bug-free navigation
    + Seeded with info to demonstrate this feature

- [x] Correctly formatted
    - [x] MVPs are listed in an ordered list
    - [x] Each MVP is broken down into bullet points

# Comments:
- Search should be considered bonus. I think you can get to it and complete it but it's generally an entire MVP, thus it should be bonus for you. 
  - In the meantime, I would remove the reference of `search` from the individual MVPs and add a `Bonus` section that has search. You should also specify what all you'd like to search by. 
- How will you plan to render the photos and albums? Will this be via a user's show page? 
- Looks good! Once you finish these comment on here to let me know and then I can close the issue!

**Comment by laujonat** [comment]
I have addressed the above issues and added time estimates for each milestone. Thanks.

**Comment by ajansel** [comment]
Awesome, good work! No problem. We will discuss getting to 7 MVPs in our 1-on-1. Done here
