### ISSUE TITLE
Database Schema

### ISSUE THREAD

**Issue by ajansel** [laujonat/clickr#3]
# Database Schema
- [x] Contains correct datatypes
  - `Description` for photos and albums should probably be texts. Additionally, `body` within comments should probably be text as well. 
- [ ] Contains appropriate constraints/details
    - [x] primary key
    - [x] not null
      - These need added once you complete the table format
    - [x] unique
      - These need added once you complete the table format
    - [ ] indexed
      - These need added once you complete the table format
    - [x] foreign key
      - Albums should not have a `photo_id` foreign key. They'll `have_many :photos`
- [x] Contains bullet points after the table that state which foreign keys will reference to which table, or references to the associations which will be made
     - These need added once you complete the table format

- [x] Correctly formatted
    - [x] schema is written in a table format
      - The picture is great! You will also need to add a table (I can send you a sample so that it's easy to edit). See bluebird for an example of what the table should look like: [bluebird schema](https://github.com/appacademy/bluebird/wiki/schema)
    - [x] the table's name are `back_ticked`
    - [x] the table header column names are bolded
    - [x] columns names are lowercased and snaked_cased and `back_ticked`
# Comments:
- I would also add a `username` column for users so that it's nicer to display than email. 
- My recommendation would be to have users have `img_urls` for a profile picture. This will ensure that there are not profiles without pictures that would make the site bare. I can explain more on this when we meet as well if you'd like. There's an easy way to set a default to give you the ability to add increased flexibility later. 
- Do all photos have to have an album? If not, this will be an issue with having the `album_id` foreign key for photo unless you make it `optional`. 
- I don't think you'll need a `PhotosAlbums` join table unless I am misunderstanding some functionality.

**Comment by laujonat** [comment]
I will talk to you more in person about the PhotosAlbums table to decide whether or not it is necessary.  The main intention was to have Photos belongs_to an Album(s).   

Otherwise, I have edited the proposed changes.  Thank you.

**Comment by ajansel** [comment]
Going to wait to close this until we talk but I checked off the things that you have updated sense, great job on the table reformatting! In the meantime here are a few more small things:

- Do you think the description for an album needing to be a text? Up to you. 
- There probably needs to be an index on the combination of `photo_id` and `body` for a tag, `user_id` and `name` for album, and photoalbums maybe (we'll discuss in person) that way they can be `unique`? 
- I think `photo_id` should be removed from `photos`
- Make sure to add a bullet under photos listing what `album_id` references

**Comment by laujonat** [comment]
So I added a body field for the _albums_ as text to simulate how Flickr has decided their album feature. 
Otherwise I've added the proposed changes. Talk soon!

**Comment by ajansel** [comment]
I think you're in good shape!
